apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-aotitrdq
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-aotitrdq:bcf9574554b7ba155029fd4c2feab5639ed340a5@sha256:f3e87947fa1009226e1e57166fc62a4f4f1cd89887dcda26eb4de6933d262819
          name: container-image
